# Generated by Django 5.1.3 on 2025-11-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='numero_emergencia',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numero_personal',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
