# Generated by Django 5.0 on 2025-11-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador'), ('contadora', 'Contadora')], default='cliente', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numero_emergencia',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numero_personal',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
