# Generated by Django 5.0 on 2025-11-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_profile_role_alter_profile_numero_emergencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AlterField(
            model_name='profile',
            name='numero_emergencia',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numero_personal',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
