# Generated by Django 5.1.3 on 2025-11-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_remove_profile_role_alter_profile_numero_emergencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador'), ('contadora', 'Contadora')], default='cliente', max_length=20),
        ),
    ]
