# Generated by Django 5.0 on 2025-11-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
