# Generated by Django 5.1.6 on 2025-11-18 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_notificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='leido_por',
            field=models.ManyToManyField(blank=True, related_name='notificaciones_leidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
